version: '3'
services:
  postgresql:
    image: postgres
    container_name: DISK_back
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: DISK_back
    command: postgres
    restart: always

  redis:
    image: redis:alpine3.14
    container_name: redis-DISK_back
    ports:
      - "6379:6379"
